namjaejeon/ksmbd-tools

cifsadmin/cifsadmin.c

request full cifssrv-tools next request!
Signed-off-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>

cifssrv-tools: clean-up cifsadmin code

---

Makefile.am
README
cifsadmin/Makefile.am
cifsadmin/cifsadmin.c
cifsadmin/cifsadmin.h
cifsd/Makefile.am
cifsd/cifsd.c
cifsd/conv.c
cifsd/dcerpc.c
cifsd/dcerpc.h
cifsd/netlink.c
cifsd/netlink.h
cifsd/pipecb.c
cifsd/winreg.c
cifsd/winreg.h
cifssrvd/Makefile.am
cifsstat/Makefile.am
cifsstat/cifsstat.c
configure.ac
include/cifsd.h
include/ntlmssp.h
lib/Makefile.am
lib/libcifsd.c
smb.conf.example

Do a semi-automatic rename: cifssrv -> cifsd

cifsd-tools: rename the project

---

cifsadmin/cifsadmin.c
cifsd/cifsd.c
cifsd/winreg.c

These patch set are fixes for SVACE and KASan issues.
Please check cifsd also.

Fix svace kasan

---

lib/management/share.c

Reported-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>

cifsd-tools: add terminating NULL byte to veto list

---

smb.conf.example

Signed-off-by: Gibeom Kim <gibeomii.kim@samsung.com>

cifsd-tools: typo correction for smb.conf

---

lib/management/user.c

Reported-by: Namjae Jeon <namjae.jeon@samsung.com>

cifsd-tools: factor out user login request handling

---

.travis.yml

cifsd-tools: switch to a newew ubuntu release

---

cifsd/cifsd.c

cifsd-tools: Sergey is an idiot

---

cifsd/cifsd.c

[cifsd-worker/32287]: ERROR: Child received signal: 2 (Interrupt)
[cifsd-worker/32287]: ERROR: Child received signal: 2 (Interrupt)
BUG at file position lib/socket.c:134:release_local_port
Assertion failed: 0 (lib/socket.c: release_local_port: 134)

cifsd-tools: use atomicop to permit only one fatal signal

---

cifsadmin/cifsadmin.c

cifsd-tools: add a simple user name sanity check to cifsadmin

---

README

Signed-off-by: Namjae Jeon <linkinjeon@gmail.com>

cifsd: fix typo in README

---

cifsshareadd/cifsshareadd.c

Signed-off-by: Namjae Jeon <linkinjeon@gmail.com>

cifsd: fix wrong smb.conf location option

---

configure.ac

Signed-off-by: Namjae Jeon <linkinjeon@gmail.com>

smbd-tools: release v3.0.1 version

---

README

ksmbd-tools: update how to restart ksmbd in README file

---

configure.ac

ksmbd-tools: release 3.2.0 version

---

Documentation/configuration.txt
include/ksmbdtools.h
include/linux/ksmbd_server.h
lib/config_parser.c
mountd/ipc.c

ksmbd-tools: add share:fake_fscaps parameter

---

lib/management/share.c

ksmbd-tools: enable oplocks by default

---

configure.ac

ksmbd-tools: release 3.2.2 version

---

README

ksmbd-tools: update README

---

lib/management/share.c

Signed-off-by: weihong6 <1360854154@qq.com>

ksmbd-tools: Fixed a possible segment error

---

README

Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>

ksmbd-tools: update cifsd-tools leftover

---

include/version.h

- ksmbd-tools's build system improvements
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>

ksmbd-tools: release 3.2.6 version

---

include/version.h

Major changes are:
- add support for SMB3 multichannel.
- remove cache read/trans buffer feature.
- fix non-english share name issue.

ksmbd-tools: release 3.4.0 version

---

ksmbd.service

Creates a template ksmbd.service systemd unit file.
Packagers should edit it as their liking.
Signed-off-by: Enzo Matsumiya <ematsumiya@suse.de>

ksmbd-tools: create a sample ksmbd.service file
