namjaejeon/ksmbd-tools

cifsd/netlink.c
cifsd/netlink.h

Delete CIFSD_UEVENT_START_SMBPORT and CIFSD_UEVENT_STOP_SMBPORT.
The related functions are merged to CIFSD_UEVENT_INIT_CONNECTION
and CIFSD_UEVENT_EXIT_CONNECTION.
Please check cifsd repo also.
https://github.com/namjaejeon/cifsd/pull/28

cifsd-tools: delete START & STOP SMBPORT uevents

---

cifsd/netlink.c
cifsd/netlink.h
cifsd/pipecb.c

Because smb-port-closing will be handled by kernel side
with new version cisfd, it does not need to register
signal handler for cifsd process.
Please check namjaejeon/cifsd#30 also.

cifsd-tools: delete signal handler registration

---

cifsd/Makefile.am
cifsd/netlink.h
cifsd/pipecb.c

This patch is to add a smb2_notify implementation into cifsd.
When user daemon(cifsd) get a inotify request from kernel-side,
cifsd makes a thread that adds inotify watch.
The thread keep reading inotify events until an event,
which matches with completion filter in the notify request packet, occurs.
When an appropriate events occurs, the user daemon
send a netlink event to kernel with notify response information.
Please check cifsd's pull-request also.

cifsd-tools: implement smb2_notify command

---

cifsd/netlink.c
cifsd/pipecb.c

Delete codes that makes threads for each notify request.
Change cifsd itself to do add_watch, 
and make one child process to monitor inotify_events from all wd. 
By spliting watch registration and reading inotify events, 
it's possble to handle multiple notify requests from kernel.
cifsd make a child only when there is no one.
Once an inotify event occurs, 
the watch is deleted and the child process exits.
Please check cifsd also.

cifsd-tools: support multiple notify requests

---

cifsd/netlink.h
cifsd/pipecb.c
include/cifsd.h

Add a notify-client list to maintain sessions' information.
When an inotify event occurs, cifsd_notifyd will look up
notify client which sent a request and send a netlink response
with the inotify event information.
** Please check cifsd repo also.

cifsd-tools: support multiple sessions

---

cifsd/cifsd.c

By assigning 0 at str[strlen("sharename =")],
prevent str having wrong share name when string-length of input str
is longer than "sharename =".

cifsd-tools: fix a bug to get right share name

---

cifsd/pipecb.c

fix some assert conditions not to abort
when out_buflen = NETLINK_CIFSD_MAX_PAYLOAD.

cifsd-tools: fix assert condition

---

cifsdadmin/cifsdadmin.c
configure.ac
include/cifsdtools.h
lib/cifsdtools.c
lib/management/user.c

Fix a bunch of 32-bit related gcc warnings.

cifsd-tools: pass size_t to base64 API

---

lib/config_parser.c

Windows does not tolerate upper/lower-case share names and treats
them equally. So should we. kcifsd will send us request with share
names in lower-case.
Reported-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>

cifsd-tools: convert share names to lower-case

---

include/ipc.h
lib/management/user.c

The macro is perfetctly fine, but our static analyzer doesn't like
it:
Arithmetic operations on /void */ is a GNU C extension, which
defines the /sizeof(void)/ to be 1.

cifsd-tools: rewrite CIFSD_IPC_MSG_PAYLOAD to make static analyzer happy

---

cifsd/cifsd.c
lib/management/user.c

So we can do
PID=`cat /tmp/cifsd.lock`
kill $PID

cifsd-tools: store manager process PID in lock file

---

lib/management/share.c

We add an extra byte after veto list; include it into
shm_share_config_payload_size().

cifsd-tools: add extra byte to shm_share_config_payload_size() return

---

cifsd/rpc_srvsvc.c
include/rpc.h

totalentries
Pointer to a value that receives the total number of entries
that could have been enumerated. Note that applications should
consider this value only as a hint.
Somehow Gnome's Nautilus client does not take as a hint and
fails to parse an otherwise valid enum shares response with
a rather confusing "invalid argument" error.
Pass a proper totalentries value and make nautilus happy.

cifsd-tools: fix TotalEntries value in EnumSharesAll response

---

cifsadmin/cifsadmin.c

cifsd-tools: set a proper name for cifsadmin logger

---

cifsd/cifsd.c

Hi just some small fix to get this working on openWRT, which uses musl.
* musl does not have sys_siglist[], so use the safer strsignal() instead

cifsd: fix musl build

---

cifsadmin/user_admin.c

cifsadmin/cifsadmin -a xx2 -p sdf
[cifsdadmin/5227]: INFO: User 'xx2' added
cifsadmin/cifsadmin -u xx2 -p sdf2
[cifsdadmin/5523]: DEBUG: Update user password: xx2
[cifsdadmin/5523]: INFO: User 'xx2' updated
cifsadmin/cifsadmin -d xx2
[cifsdadmin/5583]: INFO: User 'xx2' removed

cifsd-tools: add INFO messages to cifsadmin

---

cifsd/rpc_srvsvc.c

Windows client sends read RPC request even if we returned
CIFSD_RPC_EINVALID_PARAMETER from write. Make sure we handle
it (and need to check if windows actually understand
RPC_EINVALID_PARAMETER).

cifsd-tools: handle unsupported share level requests

---

include/cifsdtools.h
include/management/share.h
lib/management/share.c

cifsd-tools: move share config defaults to share header

---

cifsadmin/cifsadmin.c
cifsadmin/user_admin.c
cifsd/cifsd.c
cifsd/ipc.c

%m is a GNU extension that is also supported by the major C libraries
(glibc, musl, uclibc-ng, BIONIC). It saves size by avoiding a function
call.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

cifsd-tools: Replace strerror(errno) with %m

---

lib/management/user.c

This reverts commit dac42869be0c013c75c279a7063583665f46431c.

Revert "cifsd-tools: password hash size should be 16"

---

cifsshareadd/Makefile.am
cifsuseradd/Makefile.am
configure.ac

Signed-off-by: Andy Walsh <andy.walsh44@gmail.com>
Signed-off-by: Namjae Jeon <linkinjeon@gmail.com>

cifsd-tools: remove unneeded libnl for cifsuseradd and cifsshareadd

---

Makefile.am
README
configure.ac
control/Makefile.am
control/control.c

This patch add ksmbd.control util. It support the following functions.
- Shutdown(kill) ksmbd daemon by "ksmbd.control -s" command.
- Enable/Disable debug prints as per ksmbd component by "ksmbd.control
-d "all" or -d "smb" command.
- Show ksmbd version by "ksmbd.control -c" command.
Cc: Fredrik Ternerot <fredrikt@axis.com>

ksmbd-tools: add ksmbd.control util
